Traceback (most recent call last):

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__

    self._dbapi_connection = engine.raw_connection()

                             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection

    return self.pool.connect()

           ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect

    return _ConnectionFairy._checkout(self)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__

    raise exc_value.with_traceback(exc_tb)

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get

    fairy = _ConnectionRecord.checkout(pool)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    return self._create_connection()

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 713, in checkout

    rec = pool._do_get()

          ^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get

    with util.safe_reraise():

         ^^^^^^^^^^^^^^^^^^^

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/flask_sqlalchemy/extension.py", line 868, in _call_for_binds

    getattr(metadata, op_name)(bind=engine)

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5924, in create_all

    bind._run_ddl_visitor(

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3247, in _run_ddl_visitor

    with self.begin() as conn:

         ^^^^^^^^^^^^

^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection

    return _ConnectionRecord(self)

  File "/root/.nix-profile/lib/python3.12/contextlib.py", line 137, in __enter__

    return next(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^^^

           ^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection

    return self.pool.connect()

           ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 675, in __init__

  File "/opt/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3237, in begin

